---
title: ""
author: Alexander Dank
date: December 20, 2022
output: md_document
---

## Microbial Hazards Identification Decision Support System (MIDI)

This application serves as a tool to identify microbial hazards (MHs) in food products for infants and young children up to the age of 3 through a systematic MHs analysis decision support system (DSS). 

The application is divided into five major steps that can be accessed from the left panel which include:
1.	Microbial hazards identification based on food selection and relevant hazard-food pairing
2.	Microbial hazards identification based on selected thermal or non-thermal processing techniques
3.	Microbial hazards identification based on hazard recontamination potential
4.	Microbial hazards identification based on food product characteristics and growth opportunity of hazards in selected foods 
5.	Microbial hazards identification based on association level to the selected foods
Data in detail for each step can be downloaded in text files.
For additional details and the rationale behind each step, please check the user manual on the left panel.

## Contact
The application has been developed within the Laboratory of Food Microbiology of Wageningen University & Research. For bug reports, please use the GitHub page of the application:

For other questions or comments, please contact:

 > KY Claire Yeak at kahyen.yeak@wur.nl
 
 > Alexander Dank at Alexander.dank@wur.nl